#!/bin/bash

# This is a thin wrapper around xelonmusk-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using xelonmusk-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_XELONMUSKD

# Grab the value of $REAL_XELONMUSKCLI which may be xelonmusk-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_XELONMUSKCLI}" "$@" | sed 's/\r//'
